// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cwc2PLZsWh94l2iAG0fG-7Z-3kXjDRU',
    appId: '1:731624379189:web:923a03109499fb90eaf27c',
    messagingSenderId: '731624379189',
    projectId: 'esports-4b102',
    authDomain: 'esports-4b102.firebaseapp.com',
    storageBucket: 'esports-4b102.firebasestorage.app',
    measurementId: 'G-LS4E511MQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoFW5Wx47KeCeabR-pvAYAhrfcocuqd0',
    appId: '1:731624379189:android:57ba934387291108eaf27c',
    messagingSenderId: '731624379189',
    projectId: 'esports-4b102',
    storageBucket: 'esports-4b102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyM82pUgLuqiOjQVeNqSb510hkqjKj2I',
    appId: '1:731624379189:ios:53622df7d6799cbceaf27c',
    messagingSenderId: '731624379189',
    projectId: 'esports-4b102',
    storageBucket: 'esports-4b102.firebasestorage.app',
    iosBundleId: 'com.example.esports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyM82pUgLuqiOjQVeNqSb510hkqjKj2I',
    appId: '1:731624379189:ios:53622df7d6799cbceaf27c',
    messagingSenderId: '731624379189',
    projectId: 'esports-4b102',
    storageBucket: 'esports-4b102.firebasestorage.app',
    iosBundleId: 'com.example.esports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cwc2PLZsWh94l2iAG0fG-7Z-3kXjDRU',
    appId: '1:731624379189:web:d152a16483956724eaf27c',
    messagingSenderId: '731624379189',
    projectId: 'esports-4b102',
    authDomain: 'esports-4b102.firebaseapp.com',
    storageBucket: 'esports-4b102.firebasestorage.app',
    measurementId: 'G-1FLWBG2NVW',
  );
}
